Support ESM
web-mech/badwords pull request #147
Opened 2022-04-29 18:34 UTC by reesericci

Adds support for use as an ESM module with the following syntax:

`import Filter from 'badwords'`

2023-01-05 14:29 UTC, web-mech requested changes
I think it's fine to support ESM here without needing to support both ESM + CJS. But this will need to be a part of a major release. We should also update the dependencies being `require`d here.

2024-08-08 12:29 UTC, TamimiGitHub commented
Any update on this?

2024-08-08 12:34 UTC, reesericci commented
As far as I know, this branch is working and I'm not sure what the timeline is on being merged. I'll go through and make the dependencies use ESM import though to resolve the changes requested by @web-mech .

2024-08-08 12:46 UTC, reesericci commented
Just moved everything over to ESM in this PR!

2024-08-08 12:46 UTC, reesericci commented
Just moved everything over to ESM in this PR!

2024-08-08 18:37 UTC, TamimiGitHub commented
Fantastic, thanks for that @reesericci! I'll keep an eye out on the next release

2024-08-10 01:10 UTC, web-mech commented
Thanks @reesericci , will see if we can merge this in soon

2026-07-09 04:05 UTC, nyvorin commented
Thanks — this landed a different way: 4.0.0 rewrote the package in TypeScript and ships native ESM plus a CJS compatibility build (`"type": "module"` with dual `exports`). `import { Filter } from 'bad-words'` is supported today. Closing as superseded by the 4.0.0 release.

2026-07-09 04:05 UTC, closed without merging